#!/usr/bin/env python3
"""Export data/mcp/catalog.json -> xomni-mcp-catalog.csv + docs/MCP-CATALOG.md.

Pure-stdlib, deterministic (sorted), idempotent exporter.
CSV columns: name,category,purpose,price_model,stars,verified,url
Markdown: grouped by category, table columns: name | purpose | price_model | verified
"""
import csv
import json
import os
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CATALOG = os.path.join(ROOT, "data", "mcp", "catalog.json")
CSV_OUT = os.path.join(ROOT, "data", "mcp", "xomni-mcp-catalog.csv")
MD_OUT = os.path.join(ROOT, "docs", "MCP-CATALOG.md")

CSV_COLUMNS = ["name", "category", "purpose", "price_model", "stars", "verified", "url"]


def _clean(value):
    """Normalize scalar fields: strip whitespace, collapse newlines, str() scalars."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return ""
    if isinstance(value, (int, float)):
        return str(value)
    return " ".join(str(value).split())


def main():
    with open(CATALOG, "r", encoding="utf-8") as fh:
        records = json.load(fh)
    assert isinstance(records, list), "catalog.json must be a JSON array"

    # Deterministic: sort by (category, name)
    records = sorted(records, key=lambda r: (r.get("category", ""), r.get("name", "")))

    # --- CSV export ---
    with open(CSV_OUT, "w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(CSV_COLUMNS)
        for r in records:
            writer.writerow([_clean(r.get(c)) for c in CSV_COLUMNS])

    # --- Markdown export (grouped by category) ---
    by_cat = OrderedDict()
    for r in records:
        by_cat.setdefault(r.get("category", "OTHER"), []).append(r)

    lines = []
    lines.append("# XOMNI MCP Catalog")
    lines.append("")
    lines.append(
        f"Catalog of **{len(records)}** MCP servers maintained by the XOMNI 100-Agent Program. "
        "Generated by `data/mcp/export_mcp.py` — do not edit by hand."
    )
    lines.append("")
    lines.append("## Index")
    lines.append("")
    for cat in by_cat:
        lines.append(f"- [{cat}](#{cat.lower().replace('_', '-').replace(' ', '-')}) — {len(by_cat[cat])}")
    lines.append("")

    for cat, items in by_cat.items():
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| name | purpose | price_model | verified |")
        lines.append("|---|---|---|---|")
        for r in items:
            name = _clean(r.get("name"))
            purpose = _clean(r.get("purpose"))
            price = _clean(r.get("price_model"))
            verified = _clean(r.get("verified"))
            # Escape pipe chars in markdown cells
            purpose = purpose.replace("|", "\\|")
            lines.append(f"| {name} | {purpose} | {price} | {verified} |")
        lines.append("")

    with open(MD_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    # --- Verification ---
    with open(CSV_OUT, "r", encoding="utf-8", newline="") as fh:
        rows = list(csv.reader(fh))
    csv_data_rows = len(rows) - 1
    assert rows[0] == CSV_COLUMNS, "CSV header mismatch"
    assert csv_data_rows == len(records) == 311, f"CSV rows {csv_data_rows} != 311"

    md_text = open(MD_OUT, "r", encoding="utf-8").read()
    md_table_rows = sum(1 for line in md_text.splitlines() if line.startswith("| ") and not line.startswith("| ---") and not line.startswith("| name "))
    assert md_table_rows == len(records) == 311, f"MD table rows {md_table_rows} != 311"

    print(f"catalog records : {len(records)}")
    print(f"categories      : {len(by_cat)}")
    print(f"CSV written     : {CSV_OUT} ({csv_data_rows} data rows + header = {len(rows)} lines)")
    print(f"MD  written     : {MD_OUT} ({md_table_rows} table rows, {len(by_cat)} category sections)")
    for cat, items in by_cat.items():
        print(f"  - {cat}: {len(items)}")


if __name__ == "__main__":
    main()
